const express = require("express")
const {CreateAddressDetails,getAllAddress,deleteAddressDetails,updateAddressDetails} = require("../controller/Address_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     address:
 *       type: object
 *       required:
 *         - AddressId
 *         - Country
 *         - FirstName
 *         - LastName
 *         - StreetAddress
 *         - StreetAddress2
 *         - City
 *         - State
 *         - ZipCode
 *         - PhoneNumber
 *       properties:
 *         AddressId:
 *           type: integer
 *           description: AddressId
 *         Country:
 *           type: string
 *           description: Country
 *         FirstName :
 *           type: string
 *           description: FirstName
 *         LastName :
 *           type: string
 *           description: LastName
 *         StreetAddress :
 *           type: string
 *           description: StreetAddress
 *         StreetAddress2 :
 *           type: string
 *           description: StreetAddress2
 *         City :
 *           type: string
 *           description: City
 *         State :
 *           type: string
 *           description: State
 *         ZipCode :
 *           type: string
 *           description: ZipCode
 *         PhoneNumber :
 *           type: string
 *           description: PhoneNumber
 *       example:
 *         AddressId: Autogenerated
 *         Country: India
 *         FirstName: jhon
 *         LastName: Deo
 *         Address: ABC
 *         StreetAddress: ABCPOIUY
 *         StreetAddress2: ASDFG
 *         City: Mumbai
 *         State: Maharashtra
 *         ZipCode: 123461
 *         PhoneNumber: 9874501236
 *        
 *
 */

/**
 * @swagger
 * /api/v1/getAllAddress:
 *   get:
 *     summary: get all address Details
 *     tags: [address]
 *     responses:
 *       200:
 *         description: get All address
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/address'
 */
router.route("/getAllAddress").get(getAllAddress)
/**
 * @swagger
 * /api/v1/CreateAddressDetails:
 *   post:
 *     summary: create a new address Details
 *     tags: [address]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/address'
 *     responses:
 *       200:
 *         description: address details create successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/address'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateAddressDetails").post(CreateAddressDetails)
/**
 * @swagger
 * /api/v1/updateAddressDetails:
 *   post:
 *     summary: update address Details
 *     tags: [address]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/address'
 *     responses:
 *       200:
 *         description: address update successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/address'
 *       500:
 *         description: Some server error
 */
 router.route("/updateAddressDetails").put(updateAddressDetails)
 /**
  * @swagger
  * /api/v1/deleteAddressDetails/{AddressId}:
  *   delete:
  *     summary: Delete an address
  *     tags: [address]
  *     parameters:
  *         - in: path
  *           name: AddressId
  *           required: true
  *           description: AddressId is required
  *           schema:
  *              type: string
  *     responses:
  *       200:
  *         description: address delete successfully
  *   
  */
  router.route("/deleteAddressDetails/:AddressId").delete(deleteAddressDetails)
 
module.exports = router

