const express = require("express")
const {CreateaddtoCartDetails,getAllCart,deleteCartDetails,updateCartDetails} = require("../controller/AddToCart_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     AddToCart:
 *       type: object
 *       required:
 *         - CartId
 *         - UserId
 *         - ProductId
 *       properties:
 *         CartId:
 *           type: integer
 *           description: AutoGenerated
 *         UserId:
 *           type: integer
 *           description: UserId
 *         ProductId:
 *           type: integer
 *           description: ProductId
 *       example:
 *         CartId: AutoGenerated
 *         UserId: 10012
 *         ProductId: ANBC
 *        
 *
 */

/**
 * @swagger
 * /api/v1/getAllCart:
 *   get:
 *     summary: get All Cart
 *     tags: [AddToCart]
 *     responses:
 *       200:
 *         description: get  All Cart
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/AddToCart'
 */
router.route("/getAllCart").get(getAllCart)


/**
 * @swagger
 * /api/v1/CreateaddtoCartDetails:
 *   post:
 *     summary: CreateaddtoCartDetails
 *     tags: [AddToCart]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/AddToCart'
 *     responses:
 *       200:
 *         description: AddToCart create successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/AddToCart'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateaddtoCartDetails").post(CreateaddtoCartDetails)
/**
 * @swagger
 * /api/v1/updateCartDetails:
 *   post:
 *     summary: update Cart Details
 *     tags: [AddToCart]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/AddToCart'
 *     responses:
 *       200:
 *         description: AddToCart update successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/AddToCart'
 *       500:
 *         description: Some server error
 */
 router.route("/updateCartDetails").post(updateCartDetails)
/**
 * @swagger
 * /api/v1/deleteCartDetails/{CartId}:
 *   delete:
 *     summary: Delete an Cart
 *     tags: [AddToCart]
 *     parameters:
 *         - in: path
 *           name: CartId
 *           required: true
 *           description: CartId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Cart delete successfully
 *   
 */
 router.route("/deleteCartDetails/:CartId").delete(deleteCartDetails)

module.exports = router

