const express = require("express")
const {CreatereviewDetails,getAllReview,deleteReviewDetails} = require("../controller/Review_controlller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Review:
 *       type: object
 *       required:
 *         - ReviewId
 *         - UserId
 *         - ratingNo
 *         - ProductId
 *         - Comment
 *       properties:
 *         ReviewId:
 *           type: integer
 *           description: EventId
 *         UserId:
 *           type: integer
 *           description: UserId
 *         ratingNo:
 *           type: integer
 *           description: ratingNo
 *         ProductId:
 *           type: integer
 *           description: ProductId
 *         Comment:
 *           type: string
 *           description: Comment
 *       example:
 *         ReviewId: AutoGenerated
 *         UserId : 10210
 *         ratingNo: 1
 *         ProductId : 10456
 *         Comment : opoiiuyt
 */

/**
 * @swagger
 * /api/v1/getAllReview:
 *   get:
 *     summary: getAllReview
 *     tags: [Review]
 *     responses:
 *       200:
 *         description: get All Review
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Review'
 */
 router.route("/getAllReview").get(getAllReview)
 /**
  * @swagger
  * /api/v1/CreatereviewDetails:
  *   post:
  *     summary: Create a review 
  *     tags: [Review]
  *     requestBody:
  *       required: true
  *       content:
  *         application/json:
  *           schema:
  *             $ref: '#/components/schemas/Review'
  *     responses:
  *       200:
  *         description: create Review successfull
  *         content:
  *           application/json:
  *             schema:
  *               $ref: '#/components/schemas/Review'
  *       500:
  *         description: Some server error
  */
  router.route("/CreatereviewDetails").post(CreatereviewDetails)
 /**
  * @swagger
  * /api/v1/deleteReviewDetails/{ReviewId}:
  *   delete:
  *     summary: Delete an Review
  *     tags: [Review]
  *     parameters:
  *         - in: path
  *           name: ReviewId
  *           required: true
  *           description: ReviewId is required
  *           schema:
  *              type: string
  *     responses:
  *       200:
  *         description: Review delete successfully
  *   
  */
  router.route("/deleteReviewDetails/:ReviewId").delete(deleteReviewDetails)
 
 

module.exports = router

